# Curso Básico - Machine Learning

Conjuntos
São da forma:
conjunto = {e1, e2, e3, ..., en}, em que todos os elementos do conjunto são únicos, isto é, não há elementos repetidos em um conjunto, tal como é na matemática.

In [2]:
lista = [1, 2, 4, 78, 2, 1, 4]
conjunto = set(lista)
print(conjunto)

{1, 2, 4, 78}


Como foi visto acima, podemos construir um conjunto a partir de uma lista, atravez do método set(lista).
Visível também que o conjunto eliminou os elementos repetidos, como o esperado.

In [10]:
from math import fmod

conjunto = set({})

for i in range(0, 20):
    conjunto.add(int(fmod(i, 2)))
print(conjunto)

{0, 1}


In [22]:
nome = input('Digite o seu nome: ')
letras = set(nome.strip().upper())
print('O seu nome é composto pela letra', letras)

Digite o seu nome: Ana
O seu nome é composto pela letra {'A', 'N'}


Definindo lista de forma rápida.

In [26]:
lista = [i ** 2 for i in range(0, 6)]
print(lista)

[0, 1, 4, 9, 16, 25]


Função map()

Aplica a função (que é o seu primeiro argumento) sobre o segundo argumento da função map.

In [1]:
def doisvezes(n):
    return n * 2

lista = [i for i in range(0, 6)]
lista2 = list(map(doisvezes, lista))

print(lista2)
print(type(map(doisvezes, lista)))

[0, 2, 4, 6, 8, 10]
<class 'map'>


Função lambda, que é da forma

lambda i: f(i)

Agiliza bastante, pois a função lambda nos permite definir uma função genérica em uma linha e, se aliada com a função map, tem o poder de aplicar a função sobre todos os elementos que estão a partir do segundo argumento da map().

In [36]:
lista3 = list(map(lambda i: int(i * 0.5), lista2))
print(lista3)

[0, 1, 2, 3, 4, 5]


Função filter, da forma

filter(função, argumentos)

Retorna apenas os valores que satisfazem as condições da função.

In [1]:
def par(n):
    if n % 2 == 0:
        return n
    
lista = [i for i in range(0,11)]
pares = list(filter(par, lista))
print(pares)

# ou

lista1 = list(filter(lambda i: i % 2 == 0, lista))
print(lista1)

print('Se usarmos apenas o map', list(map(lambda i: i % 2 ==0, lista)))

[2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10]
Se usarmos apenas o map [True, False, True, False, True, False, True, False, True, False, True]


In [61]:
lista = [i * (-1) ** i for i in range(0, 16)]

def positivo(n):
    if n > 0:
        return n

positivos = list(filter(positivo, lista))
print(positivos)

# ou 

positivos1 = list(filter(lambda i: i > 0, lista))
print(positivos1)

[2, 4, 6, 8, 10, 12, 14]
[2, 4, 6, 8, 10, 12, 14]


In [63]:
palavras = ['a', 'b', 'b', 'c', 'a', 'd']
palavrassemduplicadas = set(palavras)
print(palavrassemduplicadas)
l = list(palavrassemduplicadas)
print(l)

{'c', 'a', 'b', 'd'}
['c', 'a', 'b', 'd']


In [72]:
lista = [int((1/((5) ** 0.5)) * ((((1 + (5 ** 0.5)) / 2) ** i) - ((1 - (5 ** 0.5)) / 2) ** i)) for i in range(0, 11)]
divididopordois = list(map(lambda i: i / 2, lista))
print(lista)
print(divididopordois)

# ou

def divpor2(n):
    return n / 2
print(list(map(divpor2, lista)))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
[0.0, 0.5, 0.5, 1.0, 1.5, 2.5, 4.0, 6.5, 10.5, 17.0, 27.5]
[0.0, 0.5, 0.5, 1.0, 1.5, 2.5, 4.0, 6.5, 10.5, 17.0, 27.5]


In [79]:
import numpy as np
lista = [i for i in range(1, 5)]
array = np.array(lista)
print(type(array))

<class 'numpy.ndarray'>


In [82]:
from random import randint

matriz = [[randint(1, 20), randint(1, 20), randint(1, 20)], [randint(1, 20), randint(1, 20), randint(1, 20)],
         [randint(1, 20), randint(1, 20), randint(1, 20)]]
print(matriz)
array = np.array(matriz)
print(type(array))
array

[[16, 9, 13], [7, 13, 19], [17, 8, 1]]
<class 'numpy.ndarray'>


array([[16,  9, 13],
       [ 7, 13, 19],
       [17,  8,  1]])

In [83]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [84]:
np.arange(5, 20, 3)

array([ 5,  8, 11, 14, 17])

In [85]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [91]:
np.linspace(0, 12, 100) # numpy.linspace(a, b, c) gera um array de c elementos que vão de a até b. Pode servir como uma
# partição de [a, b]

array([ 0.        ,  0.12121212,  0.24242424,  0.36363636,  0.48484848,
        0.60606061,  0.72727273,  0.84848485,  0.96969697,  1.09090909,
        1.21212121,  1.33333333,  1.45454545,  1.57575758,  1.6969697 ,
        1.81818182,  1.93939394,  2.06060606,  2.18181818,  2.3030303 ,
        2.42424242,  2.54545455,  2.66666667,  2.78787879,  2.90909091,
        3.03030303,  3.15151515,  3.27272727,  3.39393939,  3.51515152,
        3.63636364,  3.75757576,  3.87878788,  4.        ,  4.12121212,
        4.24242424,  4.36363636,  4.48484848,  4.60606061,  4.72727273,
        4.84848485,  4.96969697,  5.09090909,  5.21212121,  5.33333333,
        5.45454545,  5.57575758,  5.6969697 ,  5.81818182,  5.93939394,
        6.06060606,  6.18181818,  6.3030303 ,  6.42424242,  6.54545455,
        6.66666667,  6.78787879,  6.90909091,  7.03030303,  7.15151515,
        7.27272727,  7.39393939,  7.51515152,  7.63636364,  7.75757576,
        7.87878788,  8.        ,  8.12121212,  8.24242424,  8.36

In [92]:
np.eye(4) # gera uma matriz identidade quadrada. de ordem n, np.eye(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
def square(n):
    return n ** 2
def integration(a, b, partitions):
    import numpy as np
    I = 0
    for i in np.linspace(a, b, partitions):
        I += square(i) * (b-a) / partitions
    return I
a = float(input('limite inferior: '))
b = float(input('limite superior: '))
p = int(input('partições: '))
print(f'[Numérica] Integral de x² de {a} até {b} = {integration(a, b, p)}')
print(f'[Analítica] Integral de x² de {a} até {b} = {((b ** 3) -(a ** 3)) / 3}')
print(f'O erro da integral númerica, para {p} partições é {(integration(a, b, p)-(((b ** 3) -(a ** 3)) / 3))/((((b ** 3) -(a ** 3)) / 3))}')

limite inferior: 0
limite superior: 12
partições: 50000
[Numérica] Integral de x² de 0.0 até 12.0 = 576.0057601152033
[Analítica] Integral de x² de 0.0 até 12.0 = 576.0
O erro da integral númerica, para 50000 partições é 1.0000200005756534e-05


Números aleatórios rand and randn


In [8]:
from random import randint
import numpy as np
np.random.rand(randint(1, 11))

array([0.48620169, 0.07091809, 0.70980299, 0.83225674, 0.22895048,
       0.1019326 , 0.15975186, 0.58012242, 0.56957875])

In [11]:
np.random.rand(3, 3)

array([[0.26361147, 0.07355426, 0.69382488],
       [0.83602963, 0.2064123 , 0.40657581],
       [0.91530167, 0.40937881, 0.72061685]])

In [13]:
np.random.randn(4,4)

array([[-0.43005553, -1.08698057, -0.35115082, -0.24069666],
       [-0.40421656,  1.61219532,  1.01172309,  1.67525467],
       [-0.16671132, -0.73135302,  2.14633026, -0.61948865],
       [-1.39108422,  0.13420069, -1.22995179, -1.98315295]])

In [14]:
np.random.randint(1, 10, 3)

array([9, 1, 7])

In [25]:
array = np.random.randint(0, 100, 9)
matriz = array.reshape(3,3) # Constrói uma matriz com o array que foi definido préviamente.
matriz

array([[84,  4, 45],
       [20, 83, 66],
       [35, 10, 77]])

In [4]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
matriz = vetor.reshape(3, 3)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
vetor = np.random.randint(1, 50, 9)
maior_coordenada = vetor.max()
print(maior_coordenada, vetor, vetor.argmax())
posiçao_do_valor_maximo = vetor.argmax()

42 [21 21 17 42  1 40 15 28 38] 3


In [34]:
m_cord = vetor.min()
p_m_cord = vetor.argmin()
print(m_cord, p_m_cord, vetor)

1 4 [21 21 17 42  1 40 15 28 38]


In [38]:
vetor = np.arange(0, 10)
print(f'{vetor[0]}, {vetor[-1]}, {vetor[-2]}, {vetor[3]}.\n{vetor[0:4], vetor[0:9:2]}')

0, 9, 8, 3.
(array([0, 1, 2, 3]), array([0, 2, 4, 6, 8]))


In [40]:
vetor2 = 2 * vetor[3:9:2]
vetor2

array([ 6, 10, 14])

In [10]:
vetor = np.arange(1, 10)
matriz = vetor.reshape(3, 3)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
2 * matriz[:2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [50]:
matriz[0].reshape(3, 1)

array([[1],
       [2],
       [3]])

In [53]:
matriz[0][0]
matriz[2][1]

8

In [54]:
matriz[0] * matriz[0] 

array([1, 4, 9])

In [65]:
def mult(m, n):
    import numpy as np
    l = []
    for i in range(0, 3):
        l.append(m[i] * n.reshape(1, 3))
    return np.array(l).reshape(3, 3)
    
mult(matriz, matriz[0])

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [66]:
len(matriz[0])

3

In [11]:
def multiplicaçao(m, n):
    import numpy as np
    l = []
    if len(m[0]) == len(n):
        for i in range(0, len(m)):
            l.append(m[i] * n.reshape(1, len(n)))
        return np.array(l).reshape(len(n), len(m))
    else:
        print(f'As matrizes {m} e {n} não podem ser multiplicadas, pois o número de colunas da primeira é diferente de linhas da segunda')
multiplicaçao(matriz, matriz[1]) 

array([[ 4, 10, 18],
       [16, 25, 36],
       [28, 40, 54]])

In [17]:
import numpy as np
def array_Fb(n):
    import numpy as np
    vetor = np.array([(1 / ((5) ** 0.5)) * (((1 + ((5) ** 0.5)) / 2) ** i - ((1 - ((5) ** 0.5)) / 2) ** i) for i in 
                     range(0, n)])
    return vetor
matriz1 = array_Fb(25).reshape(5, 5)
matriz2 = np.random.randint(1, 100, 5)
multiplicaçao(matriz1, matriz2)

array([[0.000000e+00, 5.900000e+01, 7.100000e+01, 8.600000e+01,
        1.650000e+02],
       [1.450000e+02, 4.720000e+02, 9.230000e+02, 9.030000e+02,
        1.870000e+03],
       [1.595000e+03, 5.251000e+03, 1.022400e+04, 1.001900e+04,
        2.073500e+04],
       [1.769000e+04, 5.823300e+04, 1.133870e+05, 1.111120e+05,
        2.299550e+05],
       [1.961850e+05, 6.458140e+05, 1.257481e+06, 1.232251e+06,
        2.550240e+06]])